/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DoctorAppointment = IDL.Record({
  'id' : IDL.Nat,
  'fee' : IDL.Nat,
  'status' : IDL.Text,
  'patientName' : IDL.Text,
  'mobile' : IDL.Text,
  'doctorName' : IDL.Text,
  'dateTime' : IDL.Int,
  'reason' : IDL.Text,
});
export const MedicineOrder = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'createdAt' : IDL.Int,
  'deliveryDate' : IDL.Int,
  'prescriptionFile' : IDL.Text,
  'address' : IDL.Text,
  'patientName' : IDL.Text,
  'mobile' : IDL.Text,
});
export const PathologyBooking = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'tests' : IDL.Vec(IDL.Text),
  'sampleCollectionType' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'patientName' : IDL.Text,
  'mobile' : IDL.Text,
  'dateTime' : IDL.Int,
});
export const UltrasoundBooking = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'scanType' : IDL.Text,
  'patientName' : IDL.Text,
  'mobile' : IDL.Text,
  'amount' : IDL.Nat,
  'dateTime' : IDL.Int,
});

export const idlService = IDL.Service({
  'createContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createDoctorAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createMedicineOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createPathologyBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Int, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createUltrasoundBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'getAllDoctorAppointments' : IDL.Func(
      [],
      [IDL.Vec(DoctorAppointment)],
      ['query'],
    ),
  'getAllMedicineOrders' : IDL.Func([], [IDL.Vec(MedicineOrder)], ['query']),
  'getAllPathologyBookings' : IDL.Func(
      [],
      [IDL.Vec(PathologyBooking)],
      ['query'],
    ),
  'getAllUltrasoundBookings' : IDL.Func(
      [],
      [IDL.Vec(UltrasoundBooking)],
      ['query'],
    ),
  'getDoctorAppointmentsByMobile' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DoctorAppointment)],
      ['query'],
    ),
  'getMedicineOrdersByMobile' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MedicineOrder)],
      ['query'],
    ),
  'getPathologyBookingsByMobile' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PathologyBooking)],
      ['query'],
    ),
  'getUltrasoundBookingsByMobile' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UltrasoundBooking)],
      ['query'],
    ),
  'updateDoctorAppointmentStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateMedicineOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updatePathologyBookingStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateUltrasoundBookingStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DoctorAppointment = IDL.Record({
    'id' : IDL.Nat,
    'fee' : IDL.Nat,
    'status' : IDL.Text,
    'patientName' : IDL.Text,
    'mobile' : IDL.Text,
    'doctorName' : IDL.Text,
    'dateTime' : IDL.Int,
    'reason' : IDL.Text,
  });
  const MedicineOrder = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'createdAt' : IDL.Int,
    'deliveryDate' : IDL.Int,
    'prescriptionFile' : IDL.Text,
    'address' : IDL.Text,
    'patientName' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const PathologyBooking = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'tests' : IDL.Vec(IDL.Text),
    'sampleCollectionType' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'patientName' : IDL.Text,
    'mobile' : IDL.Text,
    'dateTime' : IDL.Int,
  });
  const UltrasoundBooking = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'scanType' : IDL.Text,
    'patientName' : IDL.Text,
    'mobile' : IDL.Text,
    'amount' : IDL.Nat,
    'dateTime' : IDL.Int,
  });
  
  return IDL.Service({
    'createContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createDoctorAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createMedicineOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createPathologyBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Int, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createUltrasoundBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'getAllDoctorAppointments' : IDL.Func(
        [],
        [IDL.Vec(DoctorAppointment)],
        ['query'],
      ),
    'getAllMedicineOrders' : IDL.Func([], [IDL.Vec(MedicineOrder)], ['query']),
    'getAllPathologyBookings' : IDL.Func(
        [],
        [IDL.Vec(PathologyBooking)],
        ['query'],
      ),
    'getAllUltrasoundBookings' : IDL.Func(
        [],
        [IDL.Vec(UltrasoundBooking)],
        ['query'],
      ),
    'getDoctorAppointmentsByMobile' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DoctorAppointment)],
        ['query'],
      ),
    'getMedicineOrdersByMobile' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MedicineOrder)],
        ['query'],
      ),
    'getPathologyBookingsByMobile' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PathologyBooking)],
        ['query'],
      ),
    'getUltrasoundBookingsByMobile' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UltrasoundBooking)],
        ['query'],
      ),
    'updateDoctorAppointmentStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateMedicineOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updatePathologyBookingStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateUltrasoundBookingStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };