/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DoctorAppointment {
  'id' : bigint,
  'fee' : bigint,
  'status' : string,
  'patientName' : string,
  'mobile' : string,
  'doctorName' : string,
  'dateTime' : bigint,
  'reason' : string,
}
export interface MedicineOrder {
  'id' : bigint,
  'status' : string,
  'createdAt' : bigint,
  'deliveryDate' : bigint,
  'prescriptionFile' : string,
  'address' : string,
  'patientName' : string,
  'mobile' : string,
}
export interface PathologyBooking {
  'id' : bigint,
  'status' : string,
  'tests' : Array<string>,
  'sampleCollectionType' : string,
  'totalAmount' : bigint,
  'patientName' : string,
  'mobile' : string,
  'dateTime' : bigint,
}
export interface UltrasoundBooking {
  'id' : bigint,
  'status' : string,
  'scanType' : string,
  'patientName' : string,
  'mobile' : string,
  'amount' : bigint,
  'dateTime' : bigint,
}
export interface _SERVICE {
  'createContactMessage' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'createDoctorAppointment' : ActorMethod<
    [string, string, string, bigint, string, bigint],
    bigint
  >,
  'createMedicineOrder' : ActorMethod<
    [string, string, string, bigint, string],
    bigint
  >,
  'createPathologyBooking' : ActorMethod<
    [string, string, Array<string>, string, bigint, bigint],
    bigint
  >,
  'createUltrasoundBooking' : ActorMethod<
    [string, string, string, bigint, bigint],
    bigint
  >,
  'getAllDoctorAppointments' : ActorMethod<[], Array<DoctorAppointment>>,
  'getAllMedicineOrders' : ActorMethod<[], Array<MedicineOrder>>,
  'getAllPathologyBookings' : ActorMethod<[], Array<PathologyBooking>>,
  'getAllUltrasoundBookings' : ActorMethod<[], Array<UltrasoundBooking>>,
  'getDoctorAppointmentsByMobile' : ActorMethod<
    [string],
    Array<DoctorAppointment>
  >,
  'getMedicineOrdersByMobile' : ActorMethod<[string], Array<MedicineOrder>>,
  'getPathologyBookingsByMobile' : ActorMethod<
    [string],
    Array<PathologyBooking>
  >,
  'getUltrasoundBookingsByMobile' : ActorMethod<
    [string],
    Array<UltrasoundBooking>
  >,
  'updateDoctorAppointmentStatus' : ActorMethod<[bigint, string], undefined>,
  'updateMedicineOrderStatus' : ActorMethod<[bigint, string], undefined>,
  'updatePathologyBookingStatus' : ActorMethod<[bigint, string], undefined>,
  'updateUltrasoundBookingStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];