/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MedicineOrder {
    id: bigint;
    status: string;
    createdAt: bigint;
    deliveryDate: bigint;
    prescriptionFile: string;
    address: string;
    patientName: string;
    mobile: string;
}
export interface UltrasoundBooking {
    id: bigint;
    status: string;
    scanType: string;
    patientName: string;
    mobile: string;
    amount: bigint;
    dateTime: bigint;
}
export interface DoctorAppointment {
    id: bigint;
    fee: bigint;
    status: string;
    patientName: string;
    mobile: string;
    doctorName: string;
    dateTime: bigint;
    reason: string;
}
export interface PathologyBooking {
    id: bigint;
    status: string;
    tests: Array<string>;
    sampleCollectionType: string;
    totalAmount: bigint;
    patientName: string;
    mobile: string;
    dateTime: bigint;
}
export interface backendInterface {
    createContactMessage(name: string, email: string, mobile: string, message: string): Promise<void>;
    createDoctorAppointment(doctorName: string, patientName: string, mobile: string, dateTime: bigint, reason: string, fee: bigint): Promise<bigint>;
    createMedicineOrder(patientName: string, mobile: string, address: string, deliveryDate: bigint, prescriptionFile: string): Promise<bigint>;
    createPathologyBooking(patientName: string, mobile: string, tests: Array<string>, sampleCollectionType: string, dateTime: bigint, totalAmount: bigint): Promise<bigint>;
    createUltrasoundBooking(patientName: string, mobile: string, scanType: string, dateTime: bigint, amount: bigint): Promise<bigint>;
    getAllDoctorAppointments(): Promise<Array<DoctorAppointment>>;
    getAllMedicineOrders(): Promise<Array<MedicineOrder>>;
    getAllPathologyBookings(): Promise<Array<PathologyBooking>>;
    getAllUltrasoundBookings(): Promise<Array<UltrasoundBooking>>;
    getDoctorAppointmentsByMobile(mobile: string): Promise<Array<DoctorAppointment>>;
    getMedicineOrdersByMobile(mobile: string): Promise<Array<MedicineOrder>>;
    getPathologyBookingsByMobile(mobile: string): Promise<Array<PathologyBooking>>;
    getUltrasoundBookingsByMobile(mobile: string): Promise<Array<UltrasoundBooking>>;
    updateDoctorAppointmentStatus(id: bigint, status: string): Promise<void>;
    updateMedicineOrderStatus(id: bigint, status: string): Promise<void>;
    updatePathologyBookingStatus(id: bigint, status: string): Promise<void>;
    updateUltrasoundBookingStatus(id: bigint, status: string): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createContactMessage(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createContactMessage(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContactMessage(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createDoctorAppointment(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDoctorAppointment(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDoctorAppointment(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createMedicineOrder(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMedicineOrder(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMedicineOrder(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createPathologyBooking(arg0: string, arg1: string, arg2: Array<string>, arg3: string, arg4: bigint, arg5: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPathologyBooking(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPathologyBooking(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createUltrasoundBooking(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createUltrasoundBooking(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUltrasoundBooking(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async getAllDoctorAppointments(): Promise<Array<DoctorAppointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDoctorAppointments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDoctorAppointments();
            return result;
        }
    }
    async getAllMedicineOrders(): Promise<Array<MedicineOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMedicineOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMedicineOrders();
            return result;
        }
    }
    async getAllPathologyBookings(): Promise<Array<PathologyBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPathologyBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPathologyBookings();
            return result;
        }
    }
    async getAllUltrasoundBookings(): Promise<Array<UltrasoundBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUltrasoundBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUltrasoundBookings();
            return result;
        }
    }
    async getDoctorAppointmentsByMobile(arg0: string): Promise<Array<DoctorAppointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctorAppointmentsByMobile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctorAppointmentsByMobile(arg0);
            return result;
        }
    }
    async getMedicineOrdersByMobile(arg0: string): Promise<Array<MedicineOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicineOrdersByMobile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicineOrdersByMobile(arg0);
            return result;
        }
    }
    async getPathologyBookingsByMobile(arg0: string): Promise<Array<PathologyBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPathologyBookingsByMobile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPathologyBookingsByMobile(arg0);
            return result;
        }
    }
    async getUltrasoundBookingsByMobile(arg0: string): Promise<Array<UltrasoundBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUltrasoundBookingsByMobile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUltrasoundBookingsByMobile(arg0);
            return result;
        }
    }
    async updateDoctorAppointmentStatus(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDoctorAppointmentStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDoctorAppointmentStatus(arg0, arg1);
            return result;
        }
    }
    async updateMedicineOrderStatus(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMedicineOrderStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMedicineOrderStatus(arg0, arg1);
            return result;
        }
    }
    async updatePathologyBookingStatus(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePathologyBookingStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePathologyBookingStatus(arg0, arg1);
            return result;
        }
    }
    async updateUltrasoundBookingStatus(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUltrasoundBookingStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUltrasoundBookingStatus(arg0, arg1);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
